#!/usr/bin/env python3
"""Sync shared MCP servers from a neutral source into Claude and Codex config.

Default mode is check-only. Apply mode only adds or updates entries named in the
neutral source, preserves unmanaged Claude servers, and rewrites only the Codex
managed block plus duplicate unmanaged tables for those same managed names.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any


BEGIN_MARKER = "# BEGIN SHARED MCP SERVERS"
END_MARKER = "# END SHARED MCP SERVERS"
GENERATED_BY = "# Auto-generated by scripts/helpers/sync_mcp_servers.py"
MCP_TABLE_RE = re.compile(r"^\[mcp_servers\.([A-Za-z0-9_-]+)\]\s*$")


def load_json_object(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        raise SystemExit(f"missing JSON file: {path}") from None
    except json.JSONDecodeError as exc:
        raise SystemExit(f"invalid JSON in {path}: {exc}") from None
    if not isinstance(data, dict):
        raise SystemExit(f"{path} must contain a JSON object")
    return data


def load_source_servers(path: Path) -> dict[str, dict[str, Any]]:
    data = load_json_object(path)
    servers = data.get("mcpServers")
    if not isinstance(servers, dict):
        raise SystemExit(f"{path} must contain an mcpServers object")
    normalized: dict[str, dict[str, Any]] = {}
    for name, config in sorted(servers.items()):
        if not isinstance(name, str) or not name:
            raise SystemExit("MCP server names must be non-empty strings")
        if not isinstance(config, dict):
            raise SystemExit(f"mcpServers.{name} must be an object")
        normalized[name] = config
    return normalized


def desired_claude_text(path: Path, servers: dict[str, dict[str, Any]]) -> str:
    data = load_json_object(path)
    existing = data.get("mcpServers")
    if existing is None:
        existing = {}
    if not isinstance(existing, dict):
        raise SystemExit(f"{path}: mcpServers must be an object when present")
    merged = dict(existing)
    merged.update(servers)
    data["mcpServers"] = merged
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def toml_quote(value: str) -> str:
    return json.dumps(value)


def render_toml_value(value: Any) -> str:
    if isinstance(value, str):
        return toml_quote(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return "[" + ", ".join(toml_quote(item) for item in value) + "]"
    raise SystemExit(f"unsupported MCP TOML value: {value!r}")


def render_server_table(name: str, config: dict[str, Any]) -> str:
    nested: dict[str, dict[str, Any]] = {}
    scalar_items: list[tuple[str, Any]] = []
    for key, value in sorted(config.items()):
        if isinstance(value, dict):
            nested[key] = value
        else:
            scalar_items.append((key, value))

    lines = [f"[mcp_servers.{name}]"]
    for key, value in scalar_items:
        lines.append(f"{key} = {render_toml_value(value)}")

    for nested_name, nested_config in sorted(nested.items()):
        lines.append("")
        lines.append(f"[mcp_servers.{name}.{nested_name}]")
        for key, value in sorted(nested_config.items()):
            lines.append(f"{key} = {render_toml_value(value)}")
    return "\n".join(lines)


def render_codex_block(servers: dict[str, dict[str, Any]]) -> str:
    tables = [render_server_table(name, config) for name, config in sorted(servers.items())]
    body = "\n\n".join(tables)
    return "\n".join([BEGIN_MARKER, GENERATED_BY, body, END_MARKER, ""])


def remove_managed_block(text: str) -> str:
    if BEGIN_MARKER not in text and END_MARKER not in text:
        return text
    if BEGIN_MARKER not in text or END_MARKER not in text:
        raise SystemExit("Codex config has only one shared MCP marker; refusing to edit")
    before, rest = text.split(BEGIN_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)
    return before.rstrip() + "\n\n" + after.lstrip("\n")


def remove_duplicate_managed_tables(text: str, managed_names: set[str]) -> str:
    lines = text.splitlines()
    keep: list[str] = []
    index = 0
    while index < len(lines):
        match = MCP_TABLE_RE.match(lines[index])
        if not match or match.group(1) not in managed_names:
            keep.append(lines[index])
            index += 1
            continue

        index += 1
        while index < len(lines) and not lines[index].startswith("["):
            index += 1
        while keep and keep[-1] == "":
            keep.pop()
        if index < len(lines) and keep:
            keep.append("")
    return "\n".join(keep).rstrip() + "\n"


def desired_codex_text(path: Path, servers: dict[str, dict[str, Any]]) -> str:
    text = path.read_text() if path.exists() else ""
    without_block = remove_managed_block(text)
    without_duplicates = remove_duplicate_managed_tables(without_block, set(servers))
    block = render_codex_block(servers)
    if not without_duplicates.strip():
        return block
    return without_duplicates.rstrip() + "\n\n" + block


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", delete=False, dir=path.parent) as handle:
        handle.write(text)
        tmp_name = handle.name
    shutil.move(tmp_name, path)


def report_drift(label: str, current: str, desired: str) -> bool:
    if current == desired:
        print(f"{label}: up to date")
        return False
    print(f"{label} drift: update needed")
    return True


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("config/mcp-servers.json"))
    parser.add_argument(
        "--claude-settings",
        type=Path,
        default=Path("claude/settings.json"),
    )
    parser.add_argument(
        "--codex-config",
        type=Path,
        default=Path("codex/config.toml"),
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="report drift without writing")
    mode.add_argument("--apply", action="store_true", help="apply managed updates")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    servers = load_source_servers(args.source)

    desired_claude = desired_claude_text(args.claude_settings, servers)
    current_claude = args.claude_settings.read_text()
    desired_codex = desired_codex_text(args.codex_config, servers)
    current_codex = args.codex_config.read_text() if args.codex_config.exists() else ""

    claude_drift = report_drift("Claude MCP", current_claude, desired_claude)
    codex_drift = report_drift("Codex MCP", current_codex, desired_codex)

    if args.check:
        return 1 if claude_drift or codex_drift else 0

    if claude_drift:
        atomic_write(args.claude_settings, desired_claude)
    if codex_drift:
        atomic_write(args.codex_config, desired_codex)
    if claude_drift or codex_drift:
        print("Applied shared MCP updates")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
