#!/usr/bin/env bash
set -euo pipefail

# Stamp the hook's real start time BEFORE doing any work. Claude's hook timeout
# starts when this wrapper is exec'd, but the secret resolution below is a live
# network call — so a classifier that timed only from its own startup would think
# it had more of the deadline left than it does, and could be killed mid-fallback
# without writing its health file. approval_classifier.py reads this and subtracts
# it (HOOK_START_ENV there); anything that cannot parse it falls back to 0.
# EPOCHREALTIME is bash 5+; /bin/bash on macOS is 3.2 and `date +%N` is a GNU
# extension, so whole seconds are the portable floor. That is precise enough for
# a 30s budget — it can only ever under-report by <1s, never over-report.
export APPROVAL_CLASSIFIER_HOOK_START="${EPOCHREALTIME:-$(date +%s)}"

SCRIPT_PATH=$(realpath "${BASH_SOURCE[0]}")
DOT_DIR=$(cd "$(dirname "$SCRIPT_PATH")/../.." && pwd)
SECRETS_HELPER="$DOT_DIR/custom_bins/dotfiles-secrets"

# Hooks run with minimal PATH — ensure bws/sops are discoverable
for d in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin "$DOT_DIR/custom_bins"; do
  [[ -d "$d" ]] && [[ ":$PATH:" != *":$d:"* ]] && PATH="$d:$PATH"
done
export PATH

# Two things this must NOT do, both of which it used to do:
#   - silence the helper's stderr. Its diagnostics (ambiguous env name, stale
#     cache, missing BWS token) are the only signal that injection failed.
#   - treat exit 0 as success on its own. The helper can exit 0 having resolved
#     nothing, and then the wrapped command runs keyless — which is how the
#     auto-classifier failed open for ~349 denials without a single error.
# Still exec unconditionally: the wrapped command (usually the classifier) has
# its own no-key handling, and exiting non-zero here would replace a precise
# stderr message with a generic hook failure.
# Deferring to an already-set key is what lets a rotated secret persist: a
# long-lived shell exports its pre-rotation direnv snapshot and nothing here can
# tell that value is dead without a network call this hot path cannot afford.
# That case is handled downstream instead, reactively — approval_classifier.py's
# post_anthropic() re-resolves the key and retries once on an HTTP 401. Do NOT
# add a validation call here.
if [[ -z "${ANTHROPIC_API_KEY:-}" && -x "$SECRETS_HELPER" ]]; then
  if exports=$("$SECRETS_HELPER" shell ANTHROPIC_API_KEY) && [[ -n "$exports" ]]; then
    # Safe here: output is generated by our own helper with shell escaping.
    eval "$exports"
  else
    echo "with-anthropic-key.sh: could not resolve ANTHROPIC_API_KEY (see above); running without it." >&2
  fi
fi

exec "$@"
