#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH=$(realpath "${BASH_SOURCE[0]}")
DOT_DIR=$(cd "$(dirname "$SCRIPT_PATH")/../.." && pwd)
SECRETS_HELPER="$DOT_DIR/custom_bins/dotfiles-secrets"

# Hooks run with minimal PATH — ensure bws/sops are discoverable
for d in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin "$DOT_DIR/custom_bins"; do
  [[ -d "$d" ]] && [[ ":$PATH:" != *":$d:"* ]] && PATH="$d:$PATH"
done
export PATH

if [[ -z "${ANTHROPIC_API_KEY:-}" && -x "$SECRETS_HELPER" ]]; then
  if exports=$("$SECRETS_HELPER" shell ANTHROPIC_API_KEY 2>/dev/null); then
    # Safe here: output is generated by our own helper with shell escaping.
    eval "$exports"
  fi
fi

exec "$@"
