# profiles.yaml — Single source of truth for Claude Code plugin profiles.
#
# Short name → qualified plugin ID (registry)
# base → always-on plugins (never repeated in profiles)
# profiles → only list what they ENABLE beyond base

registry:
  # Always-on (base)
  superpowers: superpowers@claude-plugins-official
  hookify: hookify@claude-plugins-official
  plugin-dev: plugin-dev@claude-plugins-official
  commit-commands: commit-commands@claude-plugins-official
  claude-md-management: claude-md-management@claude-plugins-official
  context7: context7@claude-plugins-official

  # Local marketplace
  code-toolkit: code-toolkit@local-marketplace
  research-toolkit: research-toolkit@local-marketplace
  writing-toolkit: writing-toolkit@local-marketplace
  workflow-toolkit: workflow-toolkit@local-marketplace
  viz-toolkit: viz-toolkit@local-marketplace

  # Official plugins
  Notion: Notion@claude-plugins-official
  figma: figma@claude-plugins-official
  ui-ux-pro-max: ui-ux-pro-max@ui-ux-pro-max-skill
  frontend-design: frontend-design@claude-plugins-official
  huggingface-skills: huggingface-skills@claude-plugins-official
  vercel: vercel@claude-plugins-official
  coderabbit: coderabbit@claude-plugins-official
  code-simplifier: code-simplifier@claude-plugins-official
  security-guidance: security-guidance@claude-plugins-official
  code-review: code-review@claude-plugins-official
  pyright-lsp: pyright-lsp@claude-plugins-official
  typescript-lsp: typescript-lsp@claude-plugins-official
  ralph-loop: ralph-loop@claude-plugins-official
  serena: serena@claude-plugins-official
  feature-dev: feature-dev@claude-plugins-official
  stripe: stripe@claude-plugins-official
  claude-code-setup: claude-code-setup@claude-plugins-official
  playwright: playwright@claude-plugins-official
  supabase: supabase@claude-plugins-official
  pr-review-toolkit: pr-review-toolkit@claude-plugins-official
  playground: playground@claude-plugins-official
  linear: linear@claude-plugins-official

# Always-on in every profile (declared once)
base:
  - superpowers
  - hookify
  - plugin-dev
  - commit-commands
  - claude-md-management
  - context7

# Profiles — only list what they ENABLE beyond base
profiles:
  code:
    comment: "Software projects"
    enable:
      - code-toolkit
      - workflow-toolkit
      - coderabbit
      - code-simplifier
      - security-guidance
      - code-review
      - feature-dev

  research:
    comment: "Experiments, evals, analysis"
    enable:
      - research-toolkit
      - writing-toolkit
      - workflow-toolkit
      - viz-toolkit
      - Notion

  writing:
    comment: "Papers, blog posts, documentation"
    enable:
      - writing-toolkit
      - viz-toolkit
      - workflow-toolkit
      - Notion

  design:
    comment: "Frontend, visualizations, web"
    enable:
      - code-toolkit
      - viz-toolkit
      - figma
      - ui-ux-pro-max
      - frontend-design
      - vercel
      - playwright

  full:
    comment: "Everything enabled (dotfiles, meta-work)"
    enable:
      - research-toolkit
      - writing-toolkit
      - code-toolkit
      - workflow-toolkit
      - viz-toolkit
      - Notion
      - coderabbit
      - code-simplifier
      - security-guidance
      - code-review

  # Sub-profiles (compose with domain)
  python:
    comment: "Adds pyright-lsp"
    enable: [pyright-lsp]

  web:
    comment: "Adds vercel, stripe, typescript-lsp, supabase"
    enable: [vercel, stripe, typescript-lsp, supabase]

  ml:
    comment: "Adds huggingface-skills"
    enable: [huggingface-skills]
