# profiles.yaml — composable plugin profiles for Claude Code.
#
# Registry is auto-discovered from installed_plugins.json.
# base → always-on plugins (never repeated in profiles)
# profiles → only list what they ENABLE beyond base

# Always-on in every profile (declared once)
base:
  - superpowers
  - hookify
  - plugin-dev
  - commit-commands
  - claude-md-management
  - context7
  - core

# Profiles — only list what they ENABLE beyond base
profiles:
  code:
    comment: "Software projects"
    enable:
      - code
      - workflow
      - coderabbit
      - code-simplifier
      - security-guidance
      - code-review
      - feature-dev

  research:
    comment: "Experiments, evals, analysis"
    enable:
      - research
      - writing
      - workflow
      - viz
      - Notion

  writing:
    comment: "Papers, blog posts, documentation"
    enable:
      - writing
      - viz
      - workflow
      - Notion

  design:
    comment: "Frontend, visualizations, web"
    enable:
      - code
      - viz
      - figma
      - ui-ux-pro-max
      - frontend-design
      - vercel
      - playwright
      - playground

  full:
    comment: "Everything enabled (dotfiles, meta-work)"
    enable:
      - research
      - writing
      - code
      - workflow
      - viz
      - Notion
      - coderabbit
      - code-simplifier
      - security-guidance
      - code-review

  # Sub-profiles (compose with domain)
  python:
    comment: "Adds pyright-lsp"
    enable: [pyright-lsp]

  web:
    comment: "Adds vercel, stripe, typescript-lsp, supabase"
    enable: [vercel, stripe, typescript-lsp, supabase]

  ml:
    comment: "Adds huggingface-skills"
    enable: [huggingface-skills]
