# profiles.yaml — composable plugin profiles for Claude Code.
#
# Registry is auto-discovered from installed_plugins.json.
# base → always-on plugins (never repeated in profiles)
# profiles → only list what they ENABLE beyond base

# Plugin marketplaces — registered + synced by `claude-context --sync`
# local: preferred when directory has .claude-plugin (live dev); github: fallback
marketplaces:
  claude-plugins-official:
    github: anthropics/claude-plugins-official

  ai-safety-plugins:
    local: ${CODE_DIR}/ai-safety-plugins
    github: yulonglin/ai-safety-plugins

  ui-ux-pro-max-skill:
    github: nextlevelbuilder/ui-ux-pro-max-skill

# Always-on in every profile (declared once)
base:
  - superpowers
  - hookify
  - plugin-dev
  - commit-commands
  - claude-md-management
  - context7
  - core

# Profiles — only list what they ENABLE beyond base
profiles:
  code:
    comment: "Software projects"
    enable:
      - code
      - workflow
      - code-simplifier
      - security-guidance

  research:
    comment: "Experiments, evals, analysis"
    enable:
      - research
      - writing
      - workflow
      - viz
      - Notion
      - linear

  writing:
    comment: "Papers, blog posts, documentation"
    enable:
      - writing
      - viz
      - workflow
      - Notion
      - linear

  design:
    comment: "Frontend, visualizations, web"
    enable:
      - code
      - viz
      - figma
      - ui-ux-pro-max
      - frontend-design
      - vercel
      - playwright
      - playground

  full:
    comment: "Everything enabled (dotfiles, meta-work)"
    enable:
      - research
      - writing
      - code
      - workflow
      - viz
      - Notion
      - linear
      - coderabbit
      - code-simplifier
      - security-guidance

  # Sub-profiles (compose with domain)
  python:
    comment: "Adds pyright-lsp"
    enable: [pyright-lsp]

  web:
    comment: "Adds vercel, typescript-lsp, supabase"
    enable: [vercel, typescript-lsp, supabase]

  ml:
    comment: "Adds huggingface-skills"
    enable: [huggingface-skills]
